application:
  authentication:
    access_token:
      jwt_secret: "Z8GJ64eimY"
      life_time: "36000000"
    refresh_token:
      jwt_secret: "Z8GJ64eimY"
      life_time: "72000000"
    share_token:
      jwt_secret: "asgsdgsgsdsg"

  i18n:
    resources:
      - classpath:core-authentication/message
      - classpath:tdl-core/message
      - classpath:core-exception/message

spring:
  application:
    name: tdl-service

  liquibase:
    changelog: classpath:/database.migration/master-changelog.xml
  datasource:
    url: jdbc:mysql://localhost:3306/tdl
    username: root
    password: ha26032003
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379


  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: maithanhha26@gmail.com
    password: mclp dlcu gmzg bktx
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
